### ISSUE TITLE
Check into apps without opening separate browser

### ISSUE THREAD

**Issue by fstonedahl** [augustanacsc490spring2019/OSL-Calendar-Android-App#13]
It needs to be super quick/easy (not require multiple steps), otherwise students may not bother. 

We should be able to make the request via the app natively, without opening chrome or whatever and possibly having to sign in again via the browser.

**Comment by kyleworkman15** [comment]
I was thinking the same thing. I thought of a possible better solution. 

So instead of embedding an entire url in the QR code, just embed in the event id and name. When the user scans the QR code, the data can be parsed directly within the app and change the database from there.

**Comment by mwardach** [comment]
This has been completed for both Android and iOS by parsing the event id from the url and reading the event name from the database.
